### ISSUE TITLE
数据集可不可以提供一个压缩包, 文件太多, 转存都转存不了, 如果能提供其他网盘链接, 比如阿里, 就更好了, 谢谢

### ISSUE THREAD

**Issue by zaqai** [AccumulateMore/CV#5]
数据集可不可以提供一个压缩包, 文件太多, 转存都转存不了, 如果能提供其他网盘链接, 比如阿里, 就更好了, 谢谢

**Comment by AccumulateMore** [comment]
① Github有单个文件上传限制，最大100M，压缩包太大了，上传不了。而且所有文件中会有大于100M的文件，所以所有文件也上传不了，只能通过网盘的形式。（这些我都试过）
② 其他初学者大概率没有其他网盘账号，让他们再去注册以及学习如何使用其他网盘，他们会觉得麻烦。而且我本地也没有数据集，都上传到百度网盘里了，我再全部下载下来再上传其他网盘也挺麻烦的。
提供思路：淘宝买一个一天的百度网盘会员，也就一元甚至几毛钱，一天足够你用会员转存并下载了。
