### ISSUE TITLE
d2l部分方法不存在，请问你是怎么下载的d2l包

### ISSUE THREAD

**Issue by kunkunsheng** [AccumulateMore/CV#7]
![image](https://github.com/AccumulateMore/CV/assets/86947725/132ee181-0311-49a1-935f-d5b00b31c638)

**Comment by AccumulateMore** [comment]
笔记 “配置版本” 那里有，我用的是当时最新版的 d2l 包，你现在下载的话，可能下载的最新版的，你下载老版本的 d2l 包试一试。
